version: "3.2"

services:
  sakura:
    build: .
    command: ["-s", "json", "-f", "config.json"]
    restart: always


  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: sakura
    ports:
      - 5432:5432