version: "3.2"

services:
  sakura:
    build: .
    command: ["-s", "json","-f","config.json"]
    restart: always
  
  database:
    image: postgres
    restart: always
    #postgresql+psycopg2://sakura:yesthisistheprodpassword@database/sakura
    environment:
      POSTGRES_PASSWORD: yesthisistheprodpassword
      POSTGRES_USER: sakura
    volumes:
      - database_data:/var/lib/postgresql
    ports:
      - 11146:5432

volumes:
  database_data: