apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: sakura-vault-secrets
spec:
  refreshInterval: 5m # Sync every 5 minutes
  secretStoreRef:
    name: oracle-cloud
    kind: ClusterSecretStore
  target:
    name: sakura
    creationPolicy: Owner
  data:
  - secretKey: discord_bot_token
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: discord.bot_token

  - secretKey: openweathermap_api_key
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: openweathermap.api_key
  
  - secretKey: tenor_api_key
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: tenor.api_key

  - secretKey: praw_client_id
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: praw.client_id

  - secretKey: praw_client_secret
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: praw.client_secret

  - secretKey: praw_username
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: praw.username

  - secretKey: praw_password
    remoteRef:
      key: ocid1.vaultsecret.oc1.ap-sydney-1.amaaaaaapgvd3siaoyqbclkswyosknlf4hlpoi6zzfjm72yeq3qokejry2sa
      version: "1"
      property: praw.password