apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
# - externalsecrets.yaml

images:
- name: sakura
  newName: ghcr.io/turbotylar/sakura
  newTag: latest
  
commonLabels:
  app: sakura