resources:
  - ../base

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: "<"
    target:
      kind: Deployment
      name: sakura

namePrefix: dev-